[package]
name = "cast"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
alloy = { version = "0.7.2", features = ["full"] }
url = "2.5.4"
clap = { version = "4.5.21", features = ["derive"] }
